//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace One.ViewsSite.User.Dashboard {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// LstUc1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::One.ViewsSite.DashBoard.Student.CourseOverView.LstUc LstUc1;
    }
}
