// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class voidAddedInManyTAbles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(voidAddedInManyTAbles));
        
        string IMigrationMetadata.Id
        {
            get { return "201605070708224_voidAddedInManyTAbles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
