// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class level_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(level_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071629098_level_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
