// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class minor_changes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minor_changes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201608281321222_minor_changes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
