// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class minor_changes_no_idea_what : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minor_changes_no_idea_what));
        
        string IMigrationMetadata.Id
        {
            get { return "201608211613457_minor_changes_no_idea_what"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
