// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class subjectSessionUser_columns_modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subjectSessionUser_columns_modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201608252129286_subjectSessionUser_columns_modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
