// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rand1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rand1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611140533251_rand1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
