// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class pass_out_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pass_out_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201611121105126_pass_out_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
