// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nullableInAssignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableInAssignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201606062022448_nullableInAssignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
