// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class many_updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(many_updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201605032026023_many_updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
