// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class file_renamed_to_userfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(file_renamed_to_userfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111138439_file_renamed_to_userfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
