// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class security_que_ans_added_in_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(security_que_ans_added_in_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201606291323440_security_que_ans_added_in_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
