// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class student_grouping_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_grouping_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201611272038001_student_grouping_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
