// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class course_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(course_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081648130_course_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
