// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class exam_type_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exam_type_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201609012300048_exam_type_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
