// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userClass_modified_and_restored_to_previous : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userClass_modified_and_restored_to_previous));
        
        string IMigrationMetadata.Id
        {
            get { return "201609110920558_userClass_modified_and_restored_to_previous"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
