// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class institution_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(institution_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201607021329413_institution_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
