// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class classUser_and_classSubject_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classUser_and_classSubject_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201608211258519_classUser_and_classSubject_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
