// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class choiceUser_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(choiceUser_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201610110232214_choiceUser_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
