// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rand : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rand));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131922343_rand"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
