// <auto-generated />
namespace Academic.Database.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class notice_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notice_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201609100448330_notice_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
